services:
  express.app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express.app
    image: tryzrxcatch/sample-app-k8s:latest

  postgres.db:
    image: postgres:15
    container_name: postgres.db.example.app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
