apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  namespace: my-app-namespace
  labels:
    app: express-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      initContainers:
        - name: migrate
          image: node:14
          command: ["sh", "-c", "npx prisma migrate deploy"]
      containers:
        - name: express-app
          image: docker.io/tryzrxcatch/sample-app-k8s
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres:5432/example"
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
